/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#16121a",
        "outline-variant": "#4c4353",
        "on-secondary-fixed": "#30004b",
        "error-container": "#93000a",
        tertiary: "#fdb969",
        "surface-container-lowest": "#110c15",
        "on-error": "#690005",
        "on-tertiary": "#482a00",
        "inverse-surface": "#eadfec",
        "surface-container-highest": "#38333c",
        "on-tertiary-container": "#ffc480",
        "on-tertiary-fixed": "#2b1700",
        "on-primary": "#4a007f",
        "secondary-container": "#633480",
        "on-surface-variant": "#cfc2d5",
        outline: "#988d9e",
        "surface-tint": "#deb7ff",
        "on-primary-container": "#e4c2ff",
        "inverse-primary": "#8234c6",
        secondary: "#e5b5ff",
        "on-error-container": "#ffdad6",
        "surface-bright": "#3d3741",
        "surface-container-high": "#2d2831",
        "on-surface-container": "#d9a4f8",
        "primary-container": "#7b2cbf",
        "tertiary-fixed-dim": "#fdb969",
        "surface-variant": "#38333c",
        "on-tertiary-fixed-variant": "#663e00",
        surface: "#16121a",
        "on-secondary": "#481965",
        "on-secondary-fixed-variant": "#60327d",
        "on-primary-fixed": "#2d0050",
        "on-background": "#eadfec",
        "inverse-on-surface": "#342e38",
        "secondary-fixed-dim": "#e5b5ff",
        "secondary-fixed": "#f4d9ff",
        "on-surface": "#eadfec",
        "surface-container": "#231e26",
        "tertiary-fixed": "#ffddba",
        primary: "#deb7ff",
        "primary-fixed-dim": "#deb7ff",
        "surface-dim": "#16121a",
        "surface-container-low": "#1f1a22",
        "tertiary-container": "#7e4d00",
        error: "#ffb4ab",
        "on-primary-fixed-variant": "#680eac",
        "primary-fixed": "#f1dbff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.0rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "80px",
        unit: "8px",
        gutter: "32px",
        "container-max": "1440px",
        "margin-mobile": "24px",
        "section-gap": "160px"
      },
      fontFamily: {
        display: ["Plus Jakarta Sans", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
